#!/usr/bin/env python3
"""Price quote writer for bean-quote command.

This module provides the QuoteWriter class which handles writing price quotes
to properly structured output files following the pattern:
$destination/quotes/$symbol/YYYYmm.beancount
"""

import os
import logging
from typing import Dict, List, Optional

from beancount.core.data import Price


class QuoteWriter:
    """A class to manage writing price quotes to destination files.
    
    This class handles the organization of price quotes into files based on
    commodity and month, creating necessary directory structures, and
    formatting the output.
    """

    def __init__(self, destination_base: str, verbose: int = 0):
        """Initialize a QuoteWriter with a base destination directory.
        
        Args:
            destination_base: The base directory for output files.
            verbose: Verbosity level for logging (0=minimal, 1=info, 2+=debug).
        """
        self.destination_base = destination_base
        self.verbose = verbose
        self.logger = logging.getLogger(__name__)

        # Create the quotes directory under the destination
        self.quotes_dir = os.path.join(destination_base, 'quotes')
        os.makedirs(self.quotes_dir, exist_ok=True)

        if self.verbose > 1:
            self.logger.debug(
                f"Initialized quote writer with base path: {self.quotes_dir}")

    def write_prices(self, prices: List[Price]) -> Dict[str, List[str]]:
        """Write price entries to appropriate destination files.
        
        Args:
            prices: List of Price directives to write.
            
        Returns:
            A dictionary mapping commodity symbols to lists of created file paths.
        """
        if not prices:
            if self.verbose > 0:
                self.logger.info("No prices to write")
            return {}

        # Group price entries by commodity and month
        price_map: Dict[str, Dict[str, List[Price]]] = {}
        for price in prices:
            symbol = price.currency
            month_key = price.date.strftime("%Y%m")

            if symbol not in price_map:
                price_map[symbol] = {}

            if month_key not in price_map[symbol]:
                price_map[symbol][month_key] = []

            price_map[symbol][month_key].append(price)

        # Track written files
        written_files: Dict[str, List[str]] = {}

        # Write each group to a separate file
        for symbol, months in price_map.items():
            # Create the directory for this symbol
            symbol_dir = os.path.join(self.quotes_dir, symbol)
            os.makedirs(symbol_dir, exist_ok=True)

            written_files[symbol] = []

            for month_key, prices in months.items():
                # Sort prices by date
                prices.sort(key=lambda p: p.date)

                # Create the file path
                file_path = os.path.join(symbol_dir, f"{month_key}.beancount")

                written_files[symbol].append(file_path)

                if self.verbose > 1:
                    self.logger.debug(
                        f"Writing {len(prices)} prices to {file_path}")

                # Write the prices to the file
                with open(file_path, 'w') as f:
                    # Add file header
                    f.write(
                        f";; Price quotes for {symbol} - {month_key[0:4]}-{month_key[4:6]}\n"
                    )
                    f.write(f";; Generated by bean-quote command\n\n")

                    for price in prices:
                        f.write(
                            f"{price.date} price {price.currency} {price.amount}\n"
                        )

            if self.verbose > 0:
                self.logger.info(
                    f"Wrote {sum(len(prices) for prices in months.values())} "
                    f"prices for {symbol} to {len(months)} files")

        return written_files

    def format_price_for_display(self, price: Price) -> str:
        """Format a price entry for display or printing.
        
        Args:
            price: The Price directive to format.
            
        Returns:
            A string representation of the price.
        """
        return f"{price.date} price {price.currency} {price.amount}"

    def get_destination_path(self, symbol: str, month_key: str) -> str:
        """Get the destination file path for a given commodity and month.
        
        Args:
            symbol: The commodity symbol.
            month_key: The month key in YYYYMM format.
            
        Returns:
            The full file path for the given commodity and month.
        """
        symbol_dir = os.path.join(self.quotes_dir, symbol)
        return os.path.join(symbol_dir, f"{month_key}.beancount")